      SUBROUTINE TMAT(E)
C     ===================
C
C     THIS SUBROUTINE DETERMINES THE OFF-SHELL TWO-BODY T-MATRIX
C     AT THE ENERGY E
C     THE SUBROUTINE F04AEF FROM THE NAG LIBRARY SOLVES THE
C     ALGEBRAIC SYSTEM  AKERN * T = V
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PARAMETER(NP1=16,NP2=18,NPTOT=1+NP1+NP2)
C
      dimension ipiv(NPTOT)
c
      DIMENSION AKERN(NPTOT,NPTOT),WKSPCE(NPTOT),
     2AA(NPTOT,NPTOT),BB(NPTOT,NPTOT)
C
      common/ppoint/P(NPTOT),P2(NPTOT),WP(NPTOT)
C
      COMMON/TM/T(NPTOT,NPTOT)
C
      COMMON/VPOT/V(NPTOT,NPTOT)
C
      DO 3 I=1,NPTOT
      DO 3 IP=1,NPTOT
      AKERN(I,IP)=-V(I,IP)*WP(IP)/(E-P2(IP))
      IF(I.EQ.IP)AKERN(I,I)=AKERN(I,I)+1.
    3 CONTINUE
      IFAIL=1
c      CALL F04AEF(AKERN,NPTOT,V,NPTOT,NPTOT,NPTOT,T,NPTOT,
c     1WKSPCE,AA,NPTOT,BB,NPTOT,IFAIL)
      AA=V
      CALL DGESV(NPTOT,NPTOT,AKERN,NPTOT,IPIV,AA,NPTOT,IFAIL)
      if (ifail.ne.0) stop
      T=AA
      RETURN
      END